[package]
name = "keylogger"
version = "0.1.0"
authors = ["Polochon-street <polochonstreet@gmx.fr>"]
edition = "2018"

[dependencies]
input = "0.4.0"
libc = "0.2.53"
udev = "0.2.0"
nix = "0.9.0"
evdev-sys = "0.2.0"
